import {
  ShieldCheck,
  Zap,
  Award,
  Layers,
  Users,
  Star,
  Clock,
  Box,
  MapPin,
  Truck,
  TruckElectric,
  Container,
  Warehouse,
  Shovel,
  Recycle,
  Trash2,
  HardHat,
  ClipboardCheck,
  Leaf,
  Ruler,
  Milestone,
  Move,
  Package,
  Cog,
  CheckCircle2,
  Phone,
  Mail,
  Menu,
  X,
  ChevronDown,
  ArrowRight,
  UploadCloud,
  Square,
  AlertTriangle,
  Cpu,
  Disc,
  Flame,
  BatteryFull,
  Syringe,
  Sprout,
  Waves,
  Mountain,
  TrendingUp,
  Trees,
  Boxes,
  Wheat,
  Armchair,
  PackagePlus,
  Magnet,
} from 'lucide-react'

const MAP = {
  priorite: Star,
  reactivite: Zap,
  experience: Award,
  polyvalence: Layers,
  pourtous: Users,
  fiabilite: ShieldCheck,
  star: Star,
  clock: Clock,
  box: Box,
  pin: MapPin,
  users: Users,
  securite: ShieldCheck,
  qualite: Award,
  delais: Clock,
  transparence: ClipboardCheck,
  environnement: Leaf,
  benne: Container,
  pelle: Shovel,
  transport: Truck,
  stockage: Warehouse,
  gravats: Ruler,
  dib: Trash2,
  chantier: HardHat,
  evacuation: Recycle,
  surface: Square,
  acces: Move,
  plate: Milestone,
  flexible: Milestone,
  porteplateau: Truck,
  grue: Move,
  plateauremorque: Container,
  remorquebachee: TruckElectric,
  pirole: Package,
  phone: Phone,
  mail: Mail,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  check: CheckCircle2,
  upload: UploadCloud,
  danger: AlertTriangle,
  electronique: Cpu,
  pneu: Disc,
  gaz: Flame,
  batterie: BatteryFull,
  medical: Syringe,
  solmeuble: Sprout,
  solargileux: Waves,
  solrocheux: Mountain,
  terrainpente: TrendingUp,
  terrainencombre: Trees,
  palette: Boxes,
  agricole: Wheat,
  mobilier: Armchair,
  diverses: PackagePlus,
  ferraille: Magnet,
}

export default function Icon({ name, className = 'h-6 w-6', strokeWidth = 1.75 }) {
  const Cmp = MAP[name] || Cog
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
